services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  rbcapp1:
    build: .
    container_name: rbcapp1
    depends_on:
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    tty: true
